version: '3'

services:

  master-node:
    image: openshift-rocky
    container_name: master-node
    tty: true
    environment:
      - ROLE=MASTER
    networks:
      okd-net:
        ipv4_address: 172.40.1.1
    volumes:
      - master-data:/root

  worker-node1:
    image: openshift-rocky
    container_name: worker-node1
    tty: true
    environment:
      - ROLE=WORKER
    networks:
      okd-net:
        ipv4_address: 172.40.1.2
    volumes:
      - worker1-data:/root

  worker-node2:
    image: openshift-rocky
    container_name: worker-node2
    tty: true
    environment:
      - ROLE=WORKER
    networks:
      okd-net:
        ipv4_address: 172.40.1.3
    volumes:
      - worker2-data:/root

networks:
  okd-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/16

volumes:
  master-data:
  worker1-data:
  worker2-data: